image: julia:1.9

pages:
  stage: deploy
  script:
    - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
    - julia --project=docs/ docs/make.jl
    - mv docs/build public  # GitLab Pages requires the folder to be named "public"
  artifacts:
    paths:
      - public
  only:
    - main  # or master, depending on your default branch name
